obstacle_range: 3.5
raytrace_range: 4.0
footprint: [[-0.14, -0.20], [-0.14, 0.22], [0.14, 0.22], [0.14, -0.20]]
inflation_radius: 2.0
transform_tolerance: 0.3

observation_sources: scan
scan:
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true

map_type: costmap
