controller_list:
  - name: fake_ur5_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_two_finger_gripper_controller
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses.
  - group: ur5_arm
    pose: rest_pose
  - group: two_finger_gripper
    pose: open